// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/about" | "/terms";
  };
  "App.jsx": {
    id: "App";
    page: "/" | "/about" | "/terms";
  };
  "src/App.jsx": {
    id: "src/App";
    page: "/";
  };
  "navbarcontent/About.jsx": {
    id: "navbarcontent/About";
    page: "/about";
  };
  "footercontent/terms.jsx": {
    id: "footercontent/terms";
    page: "/terms";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "App": typeof import("./src/App.jsx");
  "src/App": typeof import("./src/src/App.jsx");
  "navbarcontent/About": typeof import("./src/navbarcontent/About.jsx");
  "footercontent/terms": typeof import("./src/footercontent/terms.jsx");
};